// Système de langue : français / kabyle. Choix mémorisé (localStorage).
// Les chaînes marquées (i usentem) sont des propositions à relire par un locuteur.

const STRINGS = {
  fr: {
    splash_sub: "Chiffrement AES-256-GCM • Argon2id • Zéro-connaissance",
    vault_title: "🔐 Vos coffres chiffrés",
    vault_desc: "Chaque base <b>.snotevault</b> est chiffrée intégralement (AES-256-GCM, clé Argon2id).",
    unlock_pass_ph: "Mot de passe de la base",
    unlock_btn: "Déchiffrer & Ouvrir ✨",
    unlock_busy: "⏳ Déchiffrement en cours...",
    new_vault: "Créer une nouvelle base",
    vault_name_ph: "Nom de la base (ex: Perso)",
    vault_pass_ph: "Mot de passe fort (min 8 caractères)",
    create_btn: "＋ Créer la base chiffrée",
    create_busy: "⏳ Chiffrement en cours...",
    no_vault: "— aucune base, créez-en une —",
    select_base: "Sélectionnez une base",
    strength_prefix: "Force :",
    strength_levels: ["", "Très faible", "Faible", "Moyen", "Bon", "Excellent"],
    search_ph: "🔍 Recherche avancée : mots-clés...",
    search_btn: "Rechercher",
    clear_btn: "Effacer",
    graph_btn: "🕸 Graphe",
    dashboard_btn: "📊 Dashboard",
    lock_btn: "🔒 Verrouiller",
    profiles_title: "👤 Profils",
    new_profile_ph: "Nouveau profil...",
    trash_btn: "🗑 Corbeille",
    trash_count_label: "Corbeille",
    auto_lock_label: "🔒 Verrou auto",
    select_profile: "Sélectionnez un profil",
    new_note_btn: "＋ Nouvelle note",
    modal_new: "Nouvelle note",
    note_title_ph: "Titre de la note",
    note_content_ph: "Contenu... (astuce : [[Titre]] = lien, @nom = personne, 📍lieu, 💡idée)",
    tag_input_ph: "+ tag (Entrée pour ajouter)",
    wallpaper_label: "Fond :",
    glass_label: "Effet glass ✨",
    file_title: "Choisir un fichier",
    note_pass_ph: "🔒 Mot de passe individuel (optionnel)",
    edit_btn: "✏️ Modifier",
    edit_title: "Modifier la note",
    del_btn: "🗑 Corbeille",
    hl_hint: "🖍 Sélectionnez un mot/phrase puis :",
    clear_hl_btn: "🧽 Cliquez sur un surlignage pour le retirer",
    kpi_notes: "notes",
    kpi_profiles: "profils",
    kpi_words: "mots",
    kpi_attachments: "pièces jointes",
    kpi_highlights: "surlignages",
    kpi_versions: "versions",
    kpi_trash: "corbeille",
    kpi_vault: "coffre",
    dash_notes_by_profile: "📁 Notes par profil",
    dash_locked_vs_free: "🔒 Verrouillées vs libres",
    dash_locked: "verrouillée(s)",
    dash_free: "libre(s)",
    dash_activity_30d: "📈 Activité — 30 derniers jours",
    dash_activity_legend: "🟦 créations • 🟪 modifications",
    dash_tag_cloud: "🏷 Nuage de tags",
    dash_highlights_color: "🖍 Surlignages par couleur",
    dash_wallpapers: "🎨 Fonds d'écran",
    dash_security: "🛡 Sécurité du coffre",
    dash_enable: "Activer",
    dash_encryption: "Chiffrement",
    dash_file: "Fichier",
    cancel_btn: "Annuler",
    save_btn: "💾 Enregistrer (chiffré)",
    close_btn: "✕ Fermer",
    dash_top_title: "🏆 Plus longues notes",
    dash_no_tag: "Aucun tag — ajoute des #tags à tes notes !",
    profile_required: "👤 Profil requis",
    create_profile_first: "Créez d'abord un profil.",
    ok_btn: "OK",
    versions_prev: "📜 Versions précédentes",
    graph_all: "Tout",
    graph_notes: "Notes",
    graph_tags: "Tags",
    graph_mentions: "@Lieux",
    graph_persons: "@Pers",
    graph_places: "📍Lieux",
    graph_ideas: "💡Idées",
    graph_dates: "📅 Dates",
    graph_hint: "Liens [[Titre]] entre notes (les verrouillées sont exclues).",
    ins_link: "Insérer un lien [[Titre]]",
    ins_person: "Insérer une personne @nom",
    ins_place: "Insérer un lieu 📍nom",
    ins_idea: "Insérer une idée 💡nom",
    ins_date: "Insérer la date du jour AAAA-MM-JJ",
    ins_lieu: "Insérer #lieu/nom",
    ins_idee: "Insérer #idée/nom",
    dash_heatmap_title: "🗓 Heatmap d'activité — 12 semaines",
    dash_sec_autolock: "⏱ Verrou auto",
    dash_sec_inactivity: "d'inactivité",
    dash_sec_attachments: "📎 Pièces jointes",
    dash_sec_oldest: "🗓 Plus ancienne",
    dash_sec_recent: "récente",
    restore_btn: "↩ Restaurer",
    backup_title: "📦 Sauvegardes chiffrées",
    backup_now: "📦 Sauvegarder maintenant",
    decoy_configured_title: "Coffre leurre configuré.",
    decoy_desc: "Un 2e mot de passe ouvre une fausse base plausible.",
    decoy_desc_setup: "non configuré — un 2e mot de passe qui ouvre une fausse base plausible en cas de contrainte.",
    decoy_remove: "Supprimer le leurre",
    dash_sec_glass: "✨ Glass",
    dash_sec_glass_notes: "note(s)",
    dash_sec_full: "pleine(s)",
    decoy_title: "Coffre leurre",
    decoy_pass_ph: "Mot de passe leurre (min 8, différent du vrai)",
  },
  kab: {
    splash_sub: "Aḥraz s AES-256-GCM • Argon2id (i usentem)",
    vault_title: "🔐 Isenduqen-ik yettwawgelhen",
    vault_desc: "Yal azadur <b>.snotevault</b> yettwawgelhen s umata (AES-256-GCM, tasarut Argon2id). (i usentem)",
    unlock_pass_ph: "awal uffir n uzadur",
    unlock_btn: "Kkes awgelhen syin ldi ✨",
    unlock_busy: "⏳ Kkes awgelhen... (i usentem)",
    new_vault: "Snulfu-d azadur amaynut",
    vault_name_ph: "Isem n uzadur (i usentem)",
    vault_pass_ph: "Awal uffir (min 8) (i usentem)",
    create_btn: "＋ Snulfu-d azadur amaynut",
    create_busy: "⏳ Snulfu... (i usentem)",
    no_vault: "— ulac azadur, snulfu-d yiwen — (i usentem)",
    select_base: "Fren azadur (i usentem)",
    strength_prefix: "Tazmert : (i usentem)",
    strength_levels: ["", "ḍeɛif ahat", "ḍeɛif", "alemmas", "igerrez", "igerrez ahat"],
    search_ph: "🔍 Anadi s telqayt... : awalen n tsarut...",
    search_btn: "Nadi",
    clear_btn: "Sfeḍ",
    graph_btn: "🕸 Udlif",
    dashboard_btn: "📊 Tafelwit n tedbelt",
    lock_btn: "🔒 Sekkeṛ",
    profiles_title: "👤 Imeɣna",
    new_profile_ph: "Amaɣnu amaynut... (i usentem)",
    trash_btn: "🗑 Taqecwalt",
    trash_count_label: "Taqecwalt",
    auto_lock_label: "🔒 Asekkeṛ awurman",
    select_profile: "Fren amaɣnu",
    new_note_btn: "＋ Tazmilt tamaynut",
    modal_new: "Tazmilt tamaynut",
    note_title_ph: "Azwel n tezmilt",
    note_content_ph: "Agbur... ([[Azwel]] = azeɣran, @isem = amdan, 📍ideg, 💡tikti)",
    tag_input_ph: "+ tag (sit ɣef Kcem i tmerna)",
    wallpaper_label: "Agilal :",
    glass_label: "Asmaɣ ✨",
    file_title: "fren afaylu",
    note_pass_ph: "awal uffir aterras (axtiṛan)",
    edit_btn: "✏️ Ẓreg",
    edit_title: "Ẓreg tazmilt (i usentem)",
    del_btn: "🗑 Taqecwalt",
    hl_hint: "🖍 Fren awal/tafyirt syin ;",
    clear_hl_btn: "🧽 Sit ɣef usebrureq i wakken ad tekkseḍ",
    kpi_notes: "tizmilin",
    kpi_profiles: "imeɣna",
    kpi_words: "awalen",
    kpi_attachments: "tisiway yernan",
    kpi_highlights: "ticraḍ",
    kpi_versions: "ileqman",
    kpi_trash: "Taqecwalt",
    kpi_vault: "azadur (i usentem)",
    dash_notes_by_profile: "📁 Tizmilin ɣef yal amaɣnu",
    dash_locked_vs_free: "🔒 yettwasekkeṛ mgal illeli",
    dash_locked: "yettwaskkeṛ(tt-ren)",
    dash_free: "illeli(yen)",
    dash_activity_30d: "📈 Armud - 30 n wussan ineggura",
    dash_activity_legend: "🟦 asnulfu • 🟪 Isnifal",
    dash_tag_cloud: "🏷 Asigna n tags",
    dash_highlights_color: "🖍 asbrureq ɣef yal ini",
    dash_wallpapers: "🎨 Tugniwin ugilal",
    dash_security: "🛡 Taɣellist n usenduq",
    dash_enable: "Sermed",
    dash_encryption: "Awgelhen",
    dash_file: "Afaylu",
    cancel_btn: "Semmet",
    save_btn: "💾 Sekles (awgelhan)",
    close_btn: "✕ Mdel",
    dash_top_title: "🏆 tizmilin ɣezzifen akk",
    dash_no_tag: "Ulac tag - rnu #itagiyen ɣer tezmilin-ik",
    profile_required: "👤 Amaɣnu yettwasra",
    create_profile_first: "Snulfu-d deg tazwara amaɣnu",
    ok_btn: "IH",
    versions_prev: "📜 Ileqqman yezrin",
    graph_all: "Akk",
    graph_notes: "Tizmilin",
    graph_tags: "Tags",
    graph_mentions: "@Idigan",
    graph_persons: "@Imdanen",
    graph_places: "📍Idigan",
    graph_ideas: "💡Tiktiwin",
    graph_dates: "📅 Ussan",
    graph_hint: "Izeɣran [[Azwel]] gar tizmilin (timgadelt ur ttumcudunt ara). (i usentem)",
    ins_link: "Ger [[Azwel]]",
    ins_person: "Ger amdan @isem",
    ins_place: "Ger ideg 📍isem",
    ins_idea: "Ger tikti 💡isem",
    ins_date: "Ger azemz n wass-a YYYY-MM-DD",
    ins_lieu: "Ger #lieu/isem",
    ins_idee: "Ger #idée/isem",
    dash_heatmap_title: "🗓 Takerḍa n teẓɣalt n warmud — 12 imalasen",
    dash_sec_autolock: "⏱ Asekkeṛ awurman",
    dash_sec_inactivity: "d'inactivité (i usentem)",
    dash_sec_attachments: "📎 Tisiway yernan",
    dash_sec_oldest: "🗓 D aqbur ugar",
    dash_sec_recent: "récente (i usentem)",
    restore_btn: "↩ Err-d",
    backup_title: "📦 Iḥrazan yettwawgelhen",
    backup_now: "📦 Ḥrez tura",
    decoy_configured_title: "Asenduq ukellax yettuswel.",
    decoy_desc: "Awal uffir wis sin ad yeldi azadur n ukellax.",
    decoy_desc_setup: "Awal uffir wis sin ad yeldi azadur n ukellax.",
    decoy_remove: "Kkes Akellax",
    dash_sec_glass: "✨ Asmaɣ",
    dash_sec_glass_notes: "tezmilt(in)",
    dash_sec_full: "yettččur(en)",
    decoy_title: "Asenduq ukellax",
    decoy_pass_ph: "awal uffir ukellax (min 8)",
  },
};

let LANG = "fr";
const t = (key) => (STRINGS[LANG] && STRINGS[LANG][key] !== undefined ? STRINGS[LANG][key] : STRINGS.fr[key]);

function applyI18n() {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    // Bouton corbeille : préserver le compteur <span id="trashCount">
    if (el.id === "showTrashBtn") {
      const n = document.getElementById("trashCount")?.textContent ?? "0";
      el.innerHTML = `${t(el.dataset.i18n)} (<span id="trashCount">${n}</span>)`;
      return;
    }
    el.innerHTML = t(el.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-ph]").forEach((el) => { el.placeholder = t(el.dataset.i18nPh); });
  document.querySelectorAll("[data-i18n-title]").forEach((el) => { el.title = t(el.dataset.i18nTitle); });
  document.querySelectorAll("[data-lang-btn]").forEach((b) => {
    b.classList.toggle("primary", b.dataset.langBtn === LANG);
    b.classList.toggle("ghost", b.dataset.langBtn !== LANG);
  });
}

function setLang(l) {
  LANG = STRINGS[l] ? l : "fr";
  try { localStorage.setItem("sn_lang", LANG); } catch (e) {}
  applyI18n();
}
